### ISSUE TITLE
Orders should be billable based on BillingControl settings.

### ISSUE THREAD

**Issue by wolfredstep** [emoss08/Trenova#56]
**Is your feature request related to a problem? Please describe.**
Organizations should have the option to determine when to bill. 

**Describe the solution you'd like**
Currently, the `ready_to_bill` checkbox has to be true for an organization o be able to do this. We should add the ability in BillingControl for this to be if `ready_to_bill & completed`, `completed` or `ready_to_bill`.

**Comment by emoss08** [comment]
Added in https://github.com/Monta-Application/Monta/commit/be7cce3bf3b75b755e3341ab6ce9b2aba7db0974 closing.
