### ISSUE TITLE
Table Change Alerts not updated properly.

### ISSUE THREAD

**Issue by wolfredstep** [emoss08/Trenova#92]
**Describe the bug**

If you add a table change alert for 'Order' with the database action 'INSERT' it works ,but if you go back and change the 'Database Action' to 'UPDATE' at a later point the Table Change Alert is still sending 'INSERT' alerts.

**To Reproduce**
1. Go to 'Table Change Alert's'
2. Add a table change alert with any 'Database Action'
3. Update and change the database action to something else.

**Comment by emoss08** [comment]
I've fixed this issue. Will be released in the next release.
